server:
  port: 8090


spring:
  data:
    redis:
      host: 3.21.14.25
      port: 6379
      expire-time: 21600000

  datasource:
    master:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/db
        username: root
        password: 1234
    slave:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3307/db
        username: root
        password: 1234

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true

    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: namhm23@kyonggi.ac.kr
    password: qkvpxhpgyuywcbgh
    protocol: smtp
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  servlet:
    multipart:
      max-file-size: 10MB

# 포인트 메일 수신자 #
mail:
  point-mail-receiver: namhm23@naver.com

# Flask domain #
flask:
  domain: http://domain/

#p6spy 설정
decorator:
  datasource:
    p6spy:
      enable-logging: true

#JWT key
jwt:
  secret-key: abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc
  access-token-validity: 180000000
  refresh-token-validity: 259200000

# 네이버 클라우드 오브젝트 스토리지
cloud:
  aws:
    credentials:
      access-key: N3JCSJUtgse4alKEaOqX
      secret-key: rRamLrfUV8v6ZziJFEN4CVLjE9rl4kCBnEOLje5f
    stack:
      auto: false
    region:
      static: ap-northeast-2
    s3:
      endpoint: https://kr.object.ncloudstorage.com
      bucket: wswh-storage

logging:
  level:
    root: info