server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wish_hair_db
    username: root
    password: 1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        default_batch_fetch_size: 100
#        show_sql: true
#        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379
      expire-time: 21600000

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL}  # namhm23@kyonggi.ac.kr
    password: ${MAIL_PW} # qkvpxhpgyuywcbgh
    protocol: smtp
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  servlet:
    multipart:
      max-file-size: 10MB

# 포인트 메일 수신자 #
mail:
  point-mail-receiver: ${POINT_MAIL} #namhm23@naver.com

# Flask domain #
flask:
  domain: ${FLASK_DOMAIN}

# 서버 런시 발생하는 에러 로그 방지
logging:
  com:
      amazonaws:
        util:
          EC2MetadataUtils: error
  level:
    root: warn

#p6spy 설정
decorator:
  datasource:
    p6spy:
      enable-logging: false

#JWT key
jwt:
  secret-key: ${JWT_SECRET_KEY} # wishhairOiJIUzI1NiIvLoAR5cCI6IkpXSCJ9.eyJzdWIiOiIiLCLoCP1lIjoiSm9obiBEV9UiLCJpYXBCusE1MTYyMzkwMjJ9.163aevla8s7d6f987qweahqwculaoxce80k1i2o387tg
  access-token-validity: ${ACCESS_TOKEN_VALIDITY}  # 1800000
  refresh-token-validity: ${REFRESH_TOKEN_VALIDITY} # 259200000

# 네이버 클라우드 오브젝트 스토리지
cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY} # N3JCSJUtgse4alKEaOqX
      secret-key: ${S3_SECRET_KEY} #rRamLrfUV8v6ZziJFEN4CVLjE9rl4kCBnEOLje5f
    stack:
      auto: false
    region:
      static: ap-northeast-2
    s3:
      endpoint: https://kr.object.ncloudstorage.com
      bucket: ${BUCKET_NAME} # wswh-storage
