server:
  port: 8080


spring:
  data:
    redis:
      host: 3.21.14.25
      port: 6379
      expire-time: 21600000

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL}
    username: ${USERNAME}
    password: ${PW}

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true

    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PW}
    protocol: smtp
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  servlet:
    multipart:
      max-file-size: 10MB

# 포인트 메일 수신자 #
mail:
  point-mail-receiver: namhm23@naver.com

# Flask domain #
flask:
  domain: http://domain/

#p6spy 설정
decorator:
  datasource:
    p6spy:
      enable-logging: true

#JWT key
jwt:
  secret-key: ${JWT_KEY}
  access-token-validity: ${ACCESS_VALIDITY}
  refresh-token-validity: ${REFRESH_VALIDITY}

# 네이버 클라우드 오브젝트 스토리지
cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    stack:
      auto: false
    region:
      static: ap-northeast-2
    s3:
      endpoint: https://kr.object.ncloudstorage.com
      bucket: ${S3_BUCKET}
logging:
  level:
    root: info