server:
  port: 8080

spring:
  data:
    redis:
      host: 3.21.14.25
      port: 6379
      expire-time: 21600000

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_db;MODE=MySQL;
    username: sa
    password:
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true

    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: namhm23@kyonggi.ac.kr
    password: qkvpxhpgyuywcbgh
    protocol: smtp
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  servlet:
    multipart:
      max-file-size: 10MB

# 포인트 메일 수신자 #
mail:
  point-mail-receiver: namhm23@naver.com

# Flask domain #
flask:
  domain: http://domain/

# 서버 런시 발생하는 에러 로그 방지
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

#p6spy 설정
decorator:
  datasource:
    p6spy:
      enable-logging: true

#JWT key
jwt:
  secret-key: abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc
  access-token-validity: 1800000
  refresh-token-validity: 259200000

# 네이버 클라우드 오브젝트 스토리지
cloud:
  aws:
    credentials:
      access-key: N3JCSJUtgse4alKEaOqX
      secret-key: rRamLrfUV8v6ZziJFEN4CVLjE9rl4kCBnEOLje5f
    stack:
      auto: false
    region:
      static: ap-northeast-2
    s3:
      endpoint: https://kr.object.ncloudstorage.com
      bucket: wswh-storage